BEGIN;

DROP TABLE IF EXISTS core.guardians CASCADE;
DROP TABLE IF EXISTS core.students CASCADE;
DROP TABLE IF EXISTS core.family_memberships CASCADE;
DROP TABLE IF EXISTS core.families CASCADE;
DROP TABLE IF EXISTS core.auth_identities CASCADE;
DROP TABLE IF EXISTS core.users CASCADE;
DROP TABLE IF EXISTS core.members CASCADE;
DROP FUNCTION IF EXISTS core.assert_adult_account_subject() CASCADE;

DROP SCHEMA IF EXISTS domain CASCADE;
DROP SCHEMA IF EXISTS entitlement CASCADE;
DROP SCHEMA IF EXISTS audit CASCADE;
DROP SCHEMA IF EXISTS core CASCADE;

COMMIT;
