"use client";

import {useState, type ReactNode} from "react";
import Link from "next/link";
import {ArrowUpRight, ArrowRight, CalendarDays, FileCheck2, FileText, GraduationCap, ShieldCheck, Bell, Mail, Check, Plus, BookOpen, Users, ClipboardList, CircleHelp} from "lucide-react";
import {Tabs, TabsList, TabsTrigger, TabsContent} from "@/components/ui/tabs";
import {Select, SelectTrigger, SelectValue, SelectContent, SelectItem} from "@/components/ui/select";
import {Checkbox} from "@/components/ui/checkbox";
import {Dialog, DialogContent, DialogTitle, DialogDescription} from "@/components/ui/dialog";
import {useFamilyDemo} from "./family-demo-provider";
import {tr, goals, members, daysUntil, demoDate, renewDemoDocument, allowedGoal, subjectRecords, compassItems, type Locale, type Goal, type HubView, type DemoDocument} from "@/lib/family-demo";

function Pick({id,label,value,onChange,items}: {id:string;label:string;value:string;onChange:(value:string)=>void;items:readonly (readonly [string,string])[]}) {
  return <div className="center-field"><label htmlFor={id}>{label}</label><Select value={value} onValueChange={onChange}><SelectTrigger id={id}><SelectValue /></SelectTrigger><SelectContent>{items.map(([v,t])=><SelectItem value={v} key={v}>{t}</SelectItem>)}</SelectContent></Select></div>;
}
function Agree({id,checked,onChange,children}: {id:string;checked:boolean;onChange:(value:boolean)=>void;children:ReactNode}) {
  return <div className="center-agree"><Checkbox id={id} checked={checked} onCheckedChange={value=>onChange(value===true)} /><label htmlFor={id}>{children}</label></div>;
}
function Panel({title,children,action}: {title:string;children:ReactNode;action?:ReactNode}) {
  return <section className="center-panel"><div className="center-panel__heading"><h2>{title}</h2>{action}</div>{children}</section>;
}
export function DemoNotice({locale}: {locale:Locale}) {
  return <p className="center-notice"><ShieldCheck size={17} aria-hidden="true" />{tr(locale,"交互预览 · 使用虚构资料；未接通真实账户、上传或邮件。刷新后重置。","Interactive preview · Fictional data; accounts, uploads and email are not connected. Refresh resets the demo.")}</p>;
}
export function AdmissionsShortcut({locale}: {locale:Locale}) {
  return <section className="admissions-shortcut shell"><div><span className="center-kicker">APPLICATION COMPASS</span><h2>{tr(locale,"准备申请本科、硕士或博士？","Planning your next degree?")}</h2><p>{tr(locale,"从你的申请目标开始。有简历可以先整理简历，没有也可以逐步填写。","Start with your goal. Begin with a CV or a short guided profile.")}</p></div><Link className="center-button center-button--primary" href={`/${locale}/admissions`}>{tr(locale,"了解升学申请","Explore admissions")}<ArrowRight size={18} /></Link></section>;
}
export function AdmissionsContent({locale}: {locale:Locale}) {
  const demo=useFamilyDemo();
  const facts: Record<Goal,[string,string][]>={
    undergraduate:[["当前课程与成绩","Current curriculum and results"],["升学、转学或升本方向","First degree, transfer or progression"],["按实际年龄确认监护安排","Guardianship based on actual age"]],
    masters:[["本科背景与语言情况","Degree background and language"],["授课型／研究型与专业意向","Taught / research and subject goals"],["在读或毕业材料分步补充","Stage-specific documents, added gradually"]],
    doctorate:[["研究方向与科研经历","Research interests and experience"],["研究计划与导师意向","Proposal and supervisor interests"],["资助需求与成果资料","Funding needs and research outputs"]],
  };
  const faq=[
    ["本科在读，应该选哪个入口？","I am an undergraduate. Which option should I choose?","按你准备申请的学位选择。准备申请硕士就选“硕士申请”；当前学段会在登记中另行填写。","Choose the degree you want to apply for. If that is a master’s, select Master’s; your current study stage is recorded separately."],
    ["没有简历或成绩不齐，可以先咨询吗？","Can I start without a CV or complete results?","可以先整理基础信息，后续补充材料。缺少的信息会列为待补充，不会被视作零分。","Start with your basic information and add documents later. Missing information stays unknown, rather than being treated as a zero."],
    ["需要先做长问卷或付费测评吗？","Do I need a long questionnaire or paid assessment first?","已有明确申请目标，可以直接进入申请咨询登记。首次登记不设置测评付费前置条件。","If you already have an application goal, go directly to the consultation intake. A paid assessment is not a prerequisite."],
    ["以后申请另一个学位，需要重新注册吗？","Will I need another account for a later degree?","规划为同一账号管理多次申请；每次申请的年份、材料与报告分别保留。目前展示的是虚构资料交互预览。","The planned service uses one account for separate applications, each with its own year, documents and report. This version is an interactive preview using fictional data."],
  ];
  return <div className="admissions-content shell"><div className="admissions-intro"><div><p className="center-kicker">YOUR NEXT CHAPTER</p><h1>{tr(locale,"下一段求学旅程，\n从这里开始。","Your next chapter\nstarts here.")}</h1><p>{tr(locale,"本科、硕士、博士申请，在同一个入口整理。先说清目标，再一步一步准备。","One place for undergraduate, master’s and doctoral applications. Clarify your goal, then prepare one step at a time.")}</p></div><aside><GraduationCap size={32}/><strong>{tr(locale,"一次建档，持续跟进","One profile. Ongoing support.")}</strong><p>{tr(locale,"申请材料、顾问进度与后续证件节点，规划在同一个家庭中心管理。","Application documents, adviser progress and later document milestones are planned in one Family Center.")}</p><Link href={`/${locale}/family-center`}>{tr(locale,"预览家庭中心","Preview Family Center")}<ArrowUpRight size={17}/></Link></aside></div>
    <div className="admissions-options">{goals.map(item=><article key={item.id}><span className="center-kicker">{item.en.toUpperCase()}</span><h2>{tr(locale,item.zh,item.en)}</h2><p>{tr(locale,...item.description)}</p><ul>{facts[item.id].map(([zh,en])=><li key={en}><Check size={17}/>{tr(locale,zh,en)}</li>)}</ul><Link className="center-button" href={`/${locale}/application`} onClick={()=>demo.setGoal(item.id)}>{tr(locale,"查看登记流程","Preview intake")}<ArrowRight size={17}/></Link></article>)}</div>
    <section className="admissions-process"><h2>{tr(locale,"每一步，都知道接下来做什么。","Know what comes next.")}</h2><ol>{[["明确目标","Choose your goal"],["整理材料","Organise documents"],["顾问审核","Adviser review"],["持续跟进","Ongoing support"]].map(([zh,en],i)=><li key={en}><span>0{i+1}</span><strong>{tr(locale,zh,en)}</strong></li>)}</ol><p>{tr(locale,"本页为候选服务流程；正式受理、顾问审核与客户账户尚待接通。","This is a candidate service flow. Live intake, adviser review and customer accounts are not connected yet.")}</p></section>
    <section className="admissions-faq"><div><p className="center-kicker">BEFORE YOU BEGIN</p><h2>{tr(locale,"先回答几个问题。","Before you begin.")}</h2></div><div>{faq.map(([zh,en,a,b])=><details key={en}><summary>{tr(locale,zh,en)}<Plus size={18}/></summary><p>{tr(locale,a,b)}</p></details>)}</div></section>
  </div>;
}

export function ApplicationIntake({locale}: {locale:Locale}) {
  const demo=useFamilyDemo();
  return <div className="intake-shell shell"><DemoNotice locale={locale}/><div className="center-breadcrumb"><Link href={`/${locale}/admissions`}>{tr(locale,"升学申请","Admissions")}</Link><span>/</span><span>{tr(locale,"登记预览","Intake preview")}</span></div><div className="intake-heading"><div><span className="center-kicker">APPLICATION COMPASS</span><h1>{tr(locale,"说说你的下一步。","Tell us about your next step.")}</h1><p>{tr(locale,"先选择申请目标，材料可以逐步补齐。","Choose your target degree. Documents can follow.")}</p></div><Link href={`/${locale}/family-center`} onClick={()=>demo.setView("services")} className="center-text-link">{tr(locale,"我的服务","My services")}<ArrowUpRight size={18}/></Link></div>
    <div className="intake-selectors"><Pick id="app-member" label={tr(locale,"演示资料主体","Demo applicant")} value={demo.memberId} onChange={demo.setMemberId} items={members.map(m=>[m.id,tr(locale,m.zh,m.en)])}/><Pick id="app-goal" label={tr(locale,"准备申请什么学位？","Which degree are you applying for?")} value={demo.goal} onChange={v=>demo.setGoal(v as Goal)} items={goals.map(g=>[g.id,tr(locale,g.zh,g.en)])}/></div>
    <IntakeForm key={`${demo.memberId}:${demo.goal}`} locale={locale}/>
  </div>;
}
function IntakeForm({locale}: {locale:Locale}) {
  const demo=useFamilyDemo();
  const person=members.find(m=>m.id===demo.memberId)!;
  const [step,setStep]=useState(0),[year,setYear]=useState("2027"),[method,setMethod]=useState("cv");
  const [currentStage,setCurrentStage]=useState(person.minor?"secondary":person.id==="demo-an"?"masters":"undergraduate");
  const [subtype,setSubtype]=useState(demo.goal==="masters"?"taught":demo.goal==="undergraduate"?"first":"research");
  const [cv,setCv]=useState(false),[transcript,setTranscript]=useState(false),[confirmed,setConfirmed]=useState(false);
  const [consent,setConsent]=useState(false),[guardian,setGuardian]=useState(false),[submitted,setSubmitted]=useState(false);
  const [error,setError]=useState("");
  const allowed=allowedGoal(person.minor,demo.goal);
  const submit=()=>{
    if(!allowed){setError(tr(locale,"当前硕士、博士登记仅提供成人示例，请选择成人资料主体。","The master’s and doctoral previews currently require an adult demo applicant."));return;}
    if(!consent||!confirmed||(person.minor&&!guardian)){setError(tr(locale,"请确认资料与服务授权，并完成适用的监护确认。","Please confirm the details, service consent and any applicable guardian confirmation."));return;}
    demo.submitApplication({memberId:person.id,goal:demo.goal,year,status:"submitted",material:cv||transcript,consent:true});
    setSubmitted(true);demo.setView("services");
  };
  if(submitted)return <div className="intake-success"><span className="center-success-icon"><Check size={28}/></span><h2>{tr(locale,"登记示例已加入“我的服务”。","Your sample intake is now in My services.")}</h2><p>{tr(locale,"这是一条本次预览中的记录，没有发送给顾问。你可以继续查看材料与进度示例。","This record exists only in this preview and was not sent to an adviser. Continue to view its document and progress examples.")}</p><Link className="center-button center-button--primary" href={`/${locale}/family-center`}>{tr(locale,"查看我的申请","View my application")}<ArrowRight size={18}/></Link></div>;
  return <div className="intake-layout"><aside className="intake-side"><ol>{[["基础信息","Your profile"],["整理材料","Documents"],["确认登记","Confirm"]].map(([zh,en],i)=><li className={step===i?"active":step>i?"complete":""} key={en}><span>{step>i?<Check size={15}/>:i+1}</span><strong>{tr(locale,zh,en)}</strong></li>)}</ol><div><ShieldCheck size={23}/><p>{tr(locale,"示例姓名和联系方式仅用于预览。此处不接收真实证件与成绩单。","Sample names and contact details are for preview only. Real documents and transcripts are not accepted here.")}</p></div></aside>
  <section className="intake-form" aria-label={tr(locale,"升学登记预览","Admissions intake preview")}>
    {!allowed?<p className="center-alert" role="alert">{tr(locale,"当前选择的是未成年示例。硕士与博士分支需切换成人资料；本科支持监护流程预览。","This is a minor demo profile. Switch to an adult for master’s or doctoral intake, or preview undergraduate guardian arrangements.")}</p>:null}
    {step===0?<><h2>{tr(locale,"先了解你的申请目标","Start with your application goal")}</h2><p>{tr(locale,"申请学位与当前学段分别记录，方便准确准备材料。","Your target degree and current study stage are recorded separately.")}</p><div className="center-fields"><div className="center-field"><label htmlFor="sample-name">{tr(locale,"姓名（虚构示例）","Name (fictional example)")}</label><input id="sample-name" value={tr(locale,person.zh,person.en)} readOnly/></div><div className="center-field"><label htmlFor="sample-contact">{tr(locale,"联系邮箱（示例）","Contact email (example)")}</label><input id="sample-contact" value="sample@example.invalid" readOnly/></div>
    <Pick id="current-stage" label={tr(locale,"目前就读／已完成的阶段","Current / completed study stage")} value={currentStage} onChange={setCurrentStage} items={[["secondary",tr(locale,"中学","Secondary")],["subdegree",tr(locale,"副学士／大专","Associate degree / diploma")],["undergraduate",tr(locale,"本科","Undergraduate")],["masters",tr(locale,"硕士","Master’s")],["working",tr(locale,"已毕业／在职","Graduate / working")]]}/><Pick id="target-year" label={tr(locale,"计划入学年份","Target intake year")} value={year} onChange={setYear} items={[["2027","2027"],["2028","2028"],["undecided",tr(locale,"暂未确定","Undecided")]]}/>
    <Pick id="programme-type" label={tr(locale,"申请方向","Application pathway")} value={subtype} onChange={setSubtype} items={demo.goal==="undergraduate"?[["first",tr(locale,"本科新生","First-year entry")],["transfer",tr(locale,"转学／升本","Transfer / progression")]]:demo.goal==="masters"?[["taught",tr(locale,"授课型硕士","Taught master’s")],["research",tr(locale,"研究型硕士","Research master’s")]]:[["research",tr(locale,"研究型博士","Research doctorate")],["professional",tr(locale,"专业博士","Professional doctorate")]]}/>
    <Pick id="entry-method" label={tr(locale,"你想如何开始？","How would you like to begin?")} value={method} onChange={setMethod} items={[["cv",tr(locale,"已有简历，先整理简历","Start with an existing CV")],["guided",tr(locale,"没有简历，引导填写","Guided profile without a CV")]]}/></div>
    {person.minor?<p className="center-callout">{tr(locale,"未成年申请：下一步需要核验监护关系与授权。家庭成员身份本身不代表拥有资料访问权。","Minor applicant: guardian relationship and consent must be verified. Family membership alone does not grant access.")}</p>:null}
    </>:null}
    {step===1?<><h2>{tr(locale,method==="cv"?"从简历开始整理":"逐步整理你的背景",method==="cv"?"Begin with your CV":"Build your profile step by step")}</h2><p>{tr(locale,"可以先登记，稍后再补充。这里使用内置虚构材料体验流程。","You can start the intake and add more later. Use built-in fictional documents to try this flow.")}</p>
    <div className="intake-material"><FileText size={24}/><div><strong>{tr(locale,"简历","CV")}</strong><p>{cv?tr(locale,"示例已添加 · 尚未解析","Sample added · not parsed"):tr(locale,"教育背景、经历与目标","Education, experience and goals")}</p></div><button className="center-button" onClick={()=>setCv(!cv)}>{cv?tr(locale,"移除示例","Remove sample"):tr(locale,"添加示例","Add sample")}</button></div>
    <div className="intake-material"><FileCheck2 size={24}/><div><strong>{tr(locale,"成绩单","Transcript")}</strong><p>{transcript?tr(locale,"示例已添加 · 待确认","Sample added · confirmation pending"):tr(locale,"按当前学段整理","Relevant to your current study stage")}</p></div><button className="center-button" onClick={()=>setTranscript(!transcript)}>{transcript?tr(locale,"移除示例","Remove sample"):tr(locale,"添加示例","Add sample")}</button></div>
    <div className="intake-checklist"><h3>{tr(locale,"后续需要了解","For the next conversation")}</h3>{(demo.goal==="doctorate"||subtype==="research"?[["研究方向与研究计划","Research interests and proposal"],["科研经历、成果与导师意向","Research experience, outputs and supervisor interests"],["资助需求与时间安排","Funding needs and timeline"]]:demo.goal==="undergraduate"?[["课程体系与考试情况","Curriculum and examinations"],["意向专业与升学路径","Subject interests and progression route"],["适用的监护安排","Applicable guardian arrangements"]]:[["学校、专业与成绩情况","Institution, subject and results"],["语言成绩与经历","Language results and experience"],["在读证明或毕业、学位材料","Enrolment or separate graduation and degree documents"]]).map(([zh,en])=><p key={en}><CircleHelp size={16}/>{tr(locale,zh,en)}</p>)}</div><p className="center-small">{tr(locale,"材料添加不等于已完成识别，也不代表报告已审核。","Adding documents does not mean they have been parsed or a report has been reviewed.")}</p></>:null}
    {step===2?<><h2>{tr(locale,"确认这次申请","Confirm this application")}</h2><dl className="center-facts"><div><dt>{tr(locale,"资料主体","Applicant")}</dt><dd>{tr(locale,person.zh,person.en)}</dd></div><div><dt>{tr(locale,"申请目标","Target degree")}</dt><dd>{tr(locale,goals.find(g=>g.id===demo.goal)!.zh,goals.find(g=>g.id===demo.goal)!.en)}</dd></div><div><dt>{tr(locale,"入学年份","Intake year")}</dt><dd>{year==="undecided"?tr(locale,"待确定","Undecided"):year}</dd></div><div><dt>{tr(locale,"材料","Documents")}</dt><dd>{cv||transcript?tr(locale,"已添加示例，待核验","Samples added, verification pending"):tr(locale,"后续补充","To follow")}</dd></div></dl>
    <Agree id="accuracy-demo" checked={confirmed} onChange={setConfirmed}>{tr(locale,"已检查本次演示资料与申请目标。","I have checked the sample details and application goal.")}</Agree><Agree id="consent-demo" checked={consent} onChange={setConsent}>{tr(locale,"演示服务授权：允许本次登记在“我的服务”中显示；可在该处撤回。没有实际对外共享。","Demo service consent: show this intake in My services, where it can be withdrawn. No external sharing occurs.")}</Agree>{person.minor?<Agree id="guardian-demo" checked={guardian} onChange={setGuardian}>{tr(locale,"体验监护授权确认；正式使用仍需核验关系与权限。","Preview guardian confirmation; real use requires relationship and permission verification.")}</Agree>:null}
    </>:null}
    {error?<p role="alert" className="center-alert">{error}</p>:null}
    <div className="intake-form__actions">{step>0?<button className="center-button" onClick={()=>{setStep(step-1);setError("");}}>{tr(locale,"上一步","Back")}</button>:<span/>}{step<2?<button disabled={!allowed} className="center-button center-button--primary" onClick={()=>setStep(step+1)}>{tr(locale,"继续","Continue")}<ArrowRight size={17}/></button>:<button disabled={!allowed} className="center-button center-button--primary" onClick={submit}>{tr(locale,"确认演示登记","Confirm demo intake")}<Check size={17}/></button>}</div>
  </section></div>;
}

export function FamilyHub({locale}: {locale:Locale}) {
  const demo=useFamilyDemo();
  const person=members.find(m=>m.id===demo.memberId)!;
  const [selectedDoc,setSelectedDoc]=useState<string|null>(null),[emailPreview,setEmailPreview]=useState(false);
  const [notice,setNotice]=useState("");
  const documents=subjectRecords(demo.documents,demo.memberId);
  const applications=subjectRecords(demo.applications,demo.memberId);
  const learning=demo.learning[demo.memberId]??{added:false,confirmed:false,report:false,handoff:null};
  const currentDoc=documents.find(d=>d.id===selectedDoc);
  const upcoming=documents.filter(d=>d.date).sort((a,b)=>a.date!.localeCompare(b.date!))[0];
  const tabs: [HubView,string,string,typeof CalendarDays][]=[["overview","总览","Overview",CalendarDays],["documents","证件与节点","Documents",ShieldCheck],["learning","学业与报告","Learning",BookOpen],["services","我的服务","Services",ClipboardList],["profile","我的资料","Profile",Users]];
  const openDoc=(doc:DemoDocument)=>setSelectedDoc(doc.id);
  const docRows=documents.map(doc=><button className="document-row" onClick={()=>openDoc(doc)} key={doc.id}><span className="document-row__icon"><ShieldCheck size={21}/></span><span><strong>{tr(locale,...doc.name)}</strong><small>{tr(locale,...doc.dateType)}</small></span><span className="document-row__date"><strong>{doc.date??tr(locale,"待核验","To verify")}</strong><small>{doc.renewed?tr(locale,"已更新示例","Updated sample"):daysUntil(doc.date)!==null?tr(locale,`剩余 ${daysUntil(doc.date)} 天`,`${daysUntil(doc.date)} days left`):tr(locale,"尚未设置日期","Date not set")}</small></span><ArrowUpRight size={16}/></button>);
  return <div className="family-hub shell"><DemoNotice locale={locale}/><header className="hub-heading"><div><p className="center-kicker">PHOENIX FAMILY OS™</p><h1>{tr(locale,`${person.zh}，重要的事都在这里。`,`${person.en}, keep what matters in view.`)}</h1><p>{tr(locale,"证件节点、求学进展与正在办理的服务。","Document milestones, learning and ongoing services.")}</p></div><Pick id="hub-member" label={tr(locale,"切换演示身份","Switch demo identity")} value={demo.memberId} onChange={id=>{demo.setMemberId(id);setSelectedDoc(null);setNotice("");}} items={members.map(m=>[m.id,`${tr(locale,m.zh,m.en)} · ${tr(locale,m.stage[0],m.stage[1])}`])}/></header>
    <div className="hub-context"><span><Users size={16}/>{person.minor?tr(locale,"监护管理视图 · 虚构授权关系","Guardian view · fictional relationship"):tr(locale,"个人管理视图 · 家庭共享需授权","Personal view · family sharing requires consent")}</span><span>{tr(locale,`演示基准日 ${demoDate}`,`Demo date ${demoDate}`)}</span></div>
    <Tabs value={demo.view} onValueChange={v=>{demo.setView(v as HubView);setNotice("");}} className="hub-tabs"><TabsList className="hub-tabs__list" aria-label={tr(locale,"家庭中心导航","Family Center navigation")}>{tabs.map(([id,zh,en,Icon])=><TabsTrigger value={id} key={id}><Icon size={18}/><span>{tr(locale,zh,en)}</span></TabsTrigger>)}</TabsList>
    <TabsContent value="overview"><div className="hub-grid"><div className="hub-main"><section className="hub-next"><div className="hub-next__top"><span><CalendarDays size={18}/>{tr(locale,"当前优先关注","Your next priority")}</span><span>{tr(locale,"虚构示例","Fictional example")}</span></div><div className="hub-next__body"><div><h2>{upcoming?tr(locale,...upcoming.name):tr(locale,"核验证件节点","Verify document milestones")}</h2><p>{upcoming?`${tr(locale,...upcoming.dateType)} · ${upcoming.date}`:tr(locale,"先确认日期来源，再安排提醒。","Confirm the source date before scheduling reminders.")}</p><button className="center-button center-button--gold" onClick={()=>upcoming?openDoc(upcoming):demo.setView("documents")}>{tr(locale,"查看节点与下一步","View milestone & next step")}<ArrowRight size={18}/></button></div>{upcoming?<div className="hub-countdown"><strong>{daysUntil(upcoming.date)}</strong><span>{tr(locale,"天后到期 · 示例","days remaining · sample")}</span></div>:null}</div></section>
      <nav className="hub-shortcuts" aria-label={tr(locale,"常用操作","Quick actions")}>{[["documents","证件与提醒","Documents & reminders",ShieldCheck],["learning","上传成绩单","Add a transcript",FileText],["services","查看办理进度","Track a service",ClipboardList]].map(([view,zh,en,Icon])=>{const I=Icon as typeof ShieldCheck;return <button key={view as string} onClick={()=>demo.setView(view as HubView)}><I size={23}/><span>{tr(locale,zh as string,en as string)}</span><ArrowUpRight size={16}/></button>;})}</nav>
      <Panel title={tr(locale,"证件与重要节点","Documents & milestones")} action={<button className="center-text-link" onClick={()=>demo.setView("documents")}>{tr(locale,"查看全部","View all")}</button>}>{docRows}</Panel>
    </div><aside className="hub-aside"><Panel title={tr(locale,"求学与申请","Study & applications")}><GraduationCap size={30} className="center-accent"/><h3>{tr(locale,person.stage[0],person.stage[1])}</h3><p>{applications.length?tr(locale,`本次预览有 ${applications.length} 条申请记录。`,`You have ${applications.length} application record(s) in this preview.`):tr(locale,"从明确目标，到整理材料与持续跟进。","From choosing a goal to documents and ongoing support.")}</p><Link className="center-button" href={`/${locale}/application`} onClick={()=>demo.setGoal(person.minor?"undergraduate":person.id==="demo-an"?"doctorate":"masters")}>{tr(locale,"体验升学登记","Try admissions intake")}<ArrowRight size={17}/></Link></Panel>
    <Panel title={tr(locale,"提醒偏好","Reminder preferences")}><div className="center-icon-heading"><Mail size={22}/><strong>{tr(locale,"重要的时间，不必靠记忆。","Keep important dates in view.")}</strong></div><p>{tr(locale,"定期摘要与临近节点邮件将在后台接通并核验邮箱后启用。","Scheduled summaries and milestone emails will become available after backend connection and email verification.")}</p><button className="center-text-link" onClick={()=>demo.setView("profile")}>{tr(locale,"预览提醒设置","Preview settings")}<ArrowUpRight size={16}/></button></Panel></aside></div>
    <Panel title={tr(locale,"最近记录","Recent activity")}><ol className="hub-timeline"><li><span>09.06</span><div><strong>{tr(locale,"进入家庭中心预览","Family Center preview opened")}</strong><p>{tr(locale,"仅包含虚构资料，尚未关联真实客户账户。","Fictional data only; no real customer account is connected.")}</p></div></li>{applications.map(a=><li key={a.id}><span>09.06</span><div><strong>{tr(locale,`${goals.find(g=>g.id===a.goal)!.zh} · ${a.status==="withdrawn"?"已撤回示例":"登记示例"}`,`${goals.find(g=>g.id===a.goal)!.en} · ${a.status==="withdrawn"?"withdrawn sample":"sample intake"}`)}</strong><p>{tr(locale,"仅在本次预览中保留。","Kept only during this preview.")}</p></div></li>)}</ol></Panel></TabsContent>
    <TabsContent value="documents"><div className="hub-grid"><Panel title={tr(locale,"我的证件与节点","My documents & milestones")}>{docRows}<p className="center-small">{tr(locale,"所有日期均为虚构示例。证件有效期、逗留期限与换领节点分别记录；未核验的日期不生成倒计时。","All dates are fictional. Document validity, permitted stay and replacement milestones are distinct; unverified dates have no countdown.")}</p></Panel><Panel title={tr(locale,"续办后如何更新","After a renewal")}><ol className="center-numbered"><li>{tr(locale,"核验新文件与适用日期","Verify the new document and date")}</li><li>{tr(locale,"确认后替换当前节点","Confirm and replace the current milestone")}</li><li>{tr(locale,"保留历史，取消旧提醒","Keep history and cancel old reminders")}</li></ol><p>{tr(locale,"打开任一有日期的证件，可体验示例更新。查看详情不会自动标记为续办完成。","Open a dated document to try a sample update. Viewing a record does not complete a renewal.")}</p></Panel></div></TabsContent>
    <TabsContent value="learning"><div className="hub-grid"><Panel title={tr(locale,"成绩单与分析报告","Transcripts & analysis")}><div className="transcript-drop"><FileText size={35}/><h3>{learning.added?tr(locale,"示例成绩单已添加","Sample transcript added"):tr(locale,"从一份成绩单，了解下一步。","Start with a transcript.")}</h3><p>{tr(locale,"本次只体验虚构成绩单；真实上传与识别尚未开放。","Try a fictional transcript. Real uploads and extraction are not available yet.")}</p><button className="center-button center-button--primary" onClick={()=>{demo.updateLearning(person.id,{added:true,confirmed:false,report:false,handoff:null});setNotice(tr(locale,"已加入虚构材料，尚待确认。","Fictional material added; confirmation pending."));}}>{tr(locale,learning.added?"重新载入示例":"添加示例成绩单",learning.added?"Reload sample":"Add sample transcript")}<Plus size={17}/></button></div>
    {learning.added?<div className="learning-extracted"><h3>{tr(locale,"先确认材料内容","Confirm the sample details")}</h3><dl className="center-facts"><div><dt>{tr(locale,"资料主体","Subject")}</dt><dd>{tr(locale,person.zh,person.en)}</dd></div><div><dt>{tr(locale,"记录范围","Record scope")}</dt><dd>{tr(locale,"单学期成绩示例","One sample term")}</dd></div><div><dt>{tr(locale,"已提供信息","Available information")}</dt><dd>{tr(locale,"科目与成绩；评分尺度待补充","Subjects and grades; grading scale missing")}</dd></div></dl><Agree id="confirm-transcript" checked={learning.confirmed} onChange={confirmed=>demo.updateLearning(person.id,{confirmed,report:false,handoff:null})}>{tr(locale,"已确认这是虚构材料；评分尺度缺失，不能据此推算录取概率。","I confirm this is fictional. The missing grading scale prevents admissions predictions.")}</Agree><button disabled={!learning.confirmed} className="center-button" onClick={()=>demo.updateLearning(person.id,{report:true})}>{tr(locale,"查看分析报告示例","View sample analysis")}<ArrowRight size={17}/></button></div>:null}
    {learning.report?<article className="sample-report"><span className="center-kicker">SAMPLE REPORT · FICTIONAL DATA</span><h3>{tr(locale,person.minor?"学习观察与下一步建议":"学业准备与下一步建议",person.minor?"Learning observations & next steps":"Academic preparation & next steps")}</h3><p>{tr(locale,"依据：当前确认的单学期示例。尚缺评分尺度、历次成绩与学习目标，不作排名、能力定性或录取判断。","Basis: the confirmed sample term. Grading scale, prior results and goals are missing. No rankings, ability labels or admissions conclusions are made.")}</p><ol><li>{tr(locale,"补充评分尺度，核对科目名称。","Add the grading scale and verify subject names.")}</li><li>{tr(locale,"结合历次材料，确认需要进一步了解的变化。","Compare prior records to identify changes worth exploring.")}</li><li>{tr(locale,"与顾问确认目标，再选择合适的学习支持。","Confirm goals with an adviser before choosing learning support.")}</li></ol><p className="center-small">{tr(locale,"这是报告结构示例，不是自动生成或已审核的客户报告。","This illustrates a report structure; it is not a generated or reviewed client report.")}</p></article>:null}</Panel>
    <Panel title={tr(locale,"把建议带入学习","Turn insights into learning")}><div className="learning-service"><BookOpen size={25}/><h3>{tr(locale,"凤启学苑","Phoenix Academic Studio")}</h3><p>{tr(locale,"课程、语言与阶段性学习支持。","Courses, language and ongoing learning support.")}</p><button disabled={!learning.report} className="center-button" onClick={()=>{demo.updateLearning(person.id,{handoff:"academy"});demo.setView("services");}}>{tr(locale,"预览服务跟进","Preview service follow-up")}</button></div><div className="learning-service"><CircleHelp size={25}/><h3>{tr(locale,"问思 ASKWISE","ASKWISE")}</h3><p>{tr(locale,"围绕具体问题，练习理解、表达与复盘。","Practise understanding, expression and reflection around specific questions.")}</p><button disabled={!learning.report} className="center-button" onClick={()=>{demo.updateLearning(person.id,{handoff:"askwise"});demo.setView("services");}}>{tr(locale,"预览学习支持","Preview learning support")}</button></div><p className="center-small">{tr(locale,"先查看报告示例，再体验服务关联。未向任何服务发送资料。","View a sample report first. No information is sent to either service.")}</p></Panel></div></TabsContent>
    <TabsContent value="services"><div className="hub-grid"><Panel title={tr(locale,"我的申请与服务","My applications & services")} action={<Link className="center-text-link" href={`/${locale}/application`}>{tr(locale,"新增登记","New intake")}<Plus size={17}/></Link>}>
    {applications.length===0?<div className="center-empty"><ClipboardList size={30}/><h3>{tr(locale,"还没有申请登记示例","No sample applications yet")}</h3><p>{tr(locale,"本科、硕士或博士申请，都回到这里跟进。","Undergraduate, master’s and doctoral applications all return here.")}</p><Link className="center-button" href={`/${locale}/application`}>{tr(locale,"体验申请登记","Try admissions intake")}</Link></div>:applications.map(a=><article className="service-record" key={a.id}><div><span className="center-kicker">{a.year==="undecided"?tr(locale,"年份待定","Year undecided"):a.year}</span><h3>{tr(locale,goals.find(g=>g.id===a.goal)!.zh,goals.find(g=>g.id===a.goal)!.en)}</h3><span className="center-pill">{a.status==="withdrawn"?tr(locale,"已撤回 · 演示","Withdrawn · demo"):tr(locale,"已登记 · 演示","Intake recorded · demo")}</span></div><p>{a.status==="withdrawn"?tr(locale,"本次示例授权已撤回，后续跟进停止。","Sample consent withdrawn; follow-up is stopped."):tr(locale,a.material?"示例材料待核验；顾问尚未接收。":"材料后续补充；顾问尚未接收。",a.material?"Sample documents await verification; no adviser has received them.":"Documents can follow; no adviser has received this intake.")}</p><ol className="service-steps"><li className="active">{tr(locale,"登记","Intake")}</li><li>{tr(locale,"材料核验","Document check")}</li><li>{tr(locale,"顾问审核","Adviser review")}</li><li>{tr(locale,"报告发布","Report release")}</li></ol>{a.status!=="withdrawn"?<button className="center-text-link" onClick={()=>demo.withdrawApplication(a.id)}>{tr(locale,"撤回本次演示授权","Withdraw demo consent")}</button>:null}</article>)}
    {learning.handoff?<article className="service-record"><span className="center-pill">{tr(locale,"关联示例 · 未提交服务","Linked sample · not sent")}</span><h3>{learning.handoff==="academy"?tr(locale,"凤启学苑 · 学习支持","Academic Studio · learning support"):tr(locale,"问思 · 学习支持","ASKWISE · learning support")}</h3><p>{tr(locale,"关联当前成员的报告示例，正式接驳时需确认服务权益与分享授权。","Linked to this member’s sample report. Live handoff requires entitlement and sharing consent.")}</p><button className="center-text-link" onClick={()=>demo.setView("learning")}>{tr(locale,"返回原报告","Return to source report")}</button></article>:null}
    </Panel><Panel title={tr(locale,"罗盘与家庭中心","Compass & Family Center")}><p>{tr(locale,"四类罗盘统一在 V5 中查看。正式测评结果尚未同步到这个预览。","Explore all four compasses in V5. Live assessment results are not synced to this preview.")}</p><div className="hub-compass-links">{compassItems.map(c=><Link href={`/${locale}/compass#${c.id}`} key={c.id}><strong>{tr(locale,c.zh,c.en)}</strong><span>{tr(locale,"查看入口说明","View entry details")}<ArrowUpRight size={16}/></span></Link>)}</div></Panel></div></TabsContent>
    <TabsContent value="profile"><div className="hub-grid"><Panel title={tr(locale,"我的资料与授权","My profile & consent")}><dl className="center-facts"><div><dt>{tr(locale,"当前成员","Current member")}</dt><dd>{tr(locale,person.zh,person.en)}</dd></div><div><dt>{tr(locale,"学段","Study stage")}</dt><dd>{tr(locale,person.stage[0],person.stage[1])}</dd></div><div><dt>{tr(locale,"资料性质","Data status")}</dt><dd>{tr(locale,"虚构演示资料","Fictional demo data")}</dd></div><div><dt>{tr(locale,"共享范围","Sharing")}</dt><dd>{tr(locale,"未向顾问或其他成员共享","Not shared with advisers or other members")}</dd></div></dl><p>{tr(locale,"实际服务中，成年客户可独立管理；监护人和其他家庭成员只查看经核验、获授权的资料。","In the planned service, adults manage their own records. Guardians and family members see only verified, authorised information.")}</p></Panel>
    <Panel title={tr(locale,"邮件提醒预览","Email reminder preview")}><p>{tr(locale,"接收邮箱：sample@example.invalid（虚构示例，未核验）。","Recipient: sample@example.invalid (fictional, unverified).")}</p><Agree id="email-opt-in" checked={demo.emailOn} onChange={demo.setEmailOn}>{tr(locale,"选择定期摘要与临近节点提醒（预览）","Choose summaries and milestone reminders (preview)")}</Agree><p className="center-callout">{tr(locale,"邮件尚未启用。正式使用需核验邮箱及接收授权；这里的选择不会发送邮件。","Email is not enabled. A verified address and recipient consent are required; this selection sends nothing.")}</p><button disabled={!demo.emailOn} className="center-button" onClick={()=>setEmailPreview(true)}><Mail size={17}/>{tr(locale,"查看邮件样例","View email example")}</button></Panel></div></TabsContent>
    </Tabs>
    {notice?<p className="center-feedback" role="status">{notice}</p>:null}
    <Dialog open={!!currentDoc} onOpenChange={open=>{if(!open)setSelectedDoc(null);}}><DialogContent className="center-dialog"><DialogTitle>{currentDoc?tr(locale,...currentDoc.name):""}</DialogTitle><DialogDescription>{tr(locale,"节点详情 · 仅使用虚构记录","Milestone details · fictional records only")}</DialogDescription>{currentDoc?<><dl className="center-facts"><div><dt>{tr(locale,"所属成员","Member")}</dt><dd>{tr(locale,person.zh,person.en)}</dd></div><div><dt>{tr(locale,...currentDoc.dateType)}</dt><dd>{currentDoc.date??tr(locale,"尚未核验","Not verified")}</dd></div><div><dt>{tr(locale,"日期来源","Source")}</dt><dd>{tr(locale,"内置虚构示例，非客户文件","Built-in sample, not a client document")}</dd></div>{currentDoc.previousDate?<div><dt>{tr(locale,"上次日期","Previous date")}</dt><dd>{currentDoc.previousDate}</dd></div>:null}</dl><p>{currentDoc.renewed?tr(locale,"演示日期已更新，旧节点提醒标记取消。新日期仅用于体验，不代表任何续签期限规则。","The sample date is updated and the old reminder is cancelled. The new date does not represent a renewal policy."):tr(locale,"实际续办完成后，应先核验新文件，再更新日期。查看详情不会改变办理状态。","After a real renewal, verify the new document before updating its date. Viewing this record changes no service status.")}</p>{currentDoc.date?<button className="center-button center-button--primary" disabled={currentDoc.renewed} onClick={()=>demo.setDocuments(docs=>docs.map(d=>d.id===currentDoc.id?renewDemoDocument(d):d))}>{currentDoc.renewed?tr(locale,"已更新示例","Sample updated"):tr(locale,"体验续办完成后的更新","Try a post-renewal sample update")}</button>:<p className="center-callout">{tr(locale,"需先确认适用的换领节点，不能自动填写“到期日”。","Verify the applicable replacement milestone; no expiry date is assumed.")}</p>}</>:null}</DialogContent></Dialog>
    <Dialog open={emailPreview} onOpenChange={setEmailPreview}><DialogContent className="center-dialog"><DialogTitle>{tr(locale,"邮件样例 · 尚未发送","Email example · not sent")}</DialogTitle><DialogDescription>{tr(locale,"主题：你有一项证件节点需要查看","Subject: A document milestone needs your attention")}</DialogDescription><p>{tr(locale,"你好，你管理的资料中有一项临近节点。请登录 Phoenix Family OS 查看详情，并确认是否需要进一步处理。","Hello, a milestone in your records is approaching. Sign in to Phoenix Family OS to review the details and any next steps.")}</p><p className="center-small">{tr(locale,"邮件不附证件号码、文件或完整家庭资料。","Emails exclude document numbers, attachments and full family details.")}</p></DialogContent></Dialog>
  </div>;
}
