const fs = require('fs')
const path = require('path')

const SOURCE_ROOT = path.resolve(__dirname, '..')
const DIST_ROOT = path.join(SOURCE_ROOT, 'dist')
const RELEASE_VERSION = '0.5.0'
const ROOT_FILES = ['app.js', 'app.json', 'app.wxss', 'project.config.json', 'sitemap.json']
const ROOT_DIRECTORIES = ['assets', 'components', 'config', 'models', 'pages', 'services', 'utils']
const EXCLUDED = new Set([
  'models/schema.js',
  'pages/admin-families',
  'pages/admin-family',
  'services/ai-provider.js',
  'services/demo-runtime.js',
  'services/insight.js',
  'services/repository.js',
  'services/store.js'
])

function invariant(condition, message) {
  if (!condition) throw new Error(message)
}

function relativeName(value) {
  return value.split(path.sep).join('/')
}

function isExcluded(relative) {
  return [...EXCLUDED].some((entry) => relative === entry || relative.startsWith(`${entry}/`))
}

function copyTree(source, destination, relative) {
  if (isExcluded(relativeName(relative))) return
  const stats = fs.statSync(source)
  if (stats.isDirectory()) {
    fs.mkdirSync(destination, { recursive: true })
    for (const name of fs.readdirSync(source)) copyTree(
      path.join(source, name), path.join(destination, name), path.join(relative, name)
    )
    return
  }
  fs.mkdirSync(path.dirname(destination), { recursive: true })
  fs.copyFileSync(source, destination)
}

function releaseRuntime(apiBaseUrl) {
  return `// Generated by scripts/build-release.js. Do not hand-edit.\nconst API_BASE_URL = ${JSON.stringify(apiBaseUrl)}\n\nfunction accountEnvironment() { return 'release' }\nfunction mode() { return 'remote' }\nfunction apiBaseUrl() { return API_BASE_URL.replace(/\\\/$/, '') }\n\nmodule.exports = { API_BASE_URL, accountEnvironment, apiBaseUrl, mode, isDemo: () => false }\n`
}

function buildRelease(options = {}) {
  const configuredApiBaseUrl = options.apiBaseUrl || process.env.PHOENIX_API_BASE_URL || ''
  const configuredAppid = options.appid || process.env.PHOENIX_MINIPROGRAM_APPID || ''
  const offlineTest = !configuredApiBaseUrl && !configuredAppid
  invariant(offlineTest || Boolean(configuredApiBaseUrl && configuredAppid),
    'PHOENIX_API_BASE_URL and PHOENIX_MINIPROGRAM_APPID must be supplied together')
  const apiBaseUrl = offlineTest ? 'https://education-compass-offline-test.invalid' : configuredApiBaseUrl
  const appid = offlineTest ? 'touristappid' : configuredAppid
  const outputDirectory = path.resolve(options.outputDirectory || path.join(DIST_ROOT, offlineTest ? 'offline-test' : 'release'))

  invariant(/^https:\/\//i.test(apiBaseUrl), 'PHOENIX_API_BASE_URL must be an HTTPS URL')
  invariant(offlineTest || /^wx[0-9a-fA-F]{16}$/.test(appid),
    'PHOENIX_MINIPROGRAM_APPID must be a non-tourist WeChat Mini Program AppID')
  invariant(outputDirectory.startsWith(`${path.resolve(DIST_ROOT)}${path.sep}`), 'release output must stay inside dist/')

  if (fs.existsSync(outputDirectory)) fs.rmSync(outputDirectory, { recursive: true, force: true })
  fs.mkdirSync(outputDirectory, { recursive: true })

  for (const name of ROOT_FILES) copyTree(path.join(SOURCE_ROOT, name), path.join(outputDirectory, name), name)
  for (const name of ROOT_DIRECTORIES) copyTree(path.join(SOURCE_ROOT, name), path.join(outputDirectory, name), name)

  const appConfigPath = path.join(outputDirectory, 'app.json')
  const appConfig = JSON.parse(fs.readFileSync(appConfigPath, 'utf8'))
  const sourcePageCount = appConfig.pages.length
  appConfig.pages = appConfig.pages.filter((page) => !page.startsWith('pages/admin-'))
  invariant(appConfig.pages.includes('pages/agent-chat/index'), 'release must include the paid-report Agent page')
  invariant(appConfig.pages.includes('pages/assessment-analysis/index'), 'release must include the dual analysis result page')
  invariant(appConfig.pages.includes('pages/compass/index'), 'release must include the Education Compass entry page')
  invariant(appConfig.pages.includes('pages/compass-questionnaire/index'), 'release must include the resumable Education Compass questionnaire')
  invariant(appConfig.pages.includes('pages/compass-preview/index'), 'release must include the locked Education Compass result page')
  fs.writeFileSync(appConfigPath, `${JSON.stringify(appConfig, null, 2)}\n`)

  const projectConfigPath = path.join(outputDirectory, 'project.config.json')
  const projectConfig = JSON.parse(fs.readFileSync(projectConfigPath, 'utf8'))
  projectConfig.appid = appid
  projectConfig.description = offlineTest
    ? `OFFLINE TEST ONLY - Phoenix Family OS V${RELEASE_VERSION}; not authorized for upload or release`
    : `Phoenix Family OS V${RELEASE_VERSION} paid Compass Agent remote release`
  projectConfig.projectname = offlineTest
    ? `Phoenix-Family-OS-V${RELEASE_VERSION}-Offline-Test-Only`
    : `Phoenix-Family-OS-V${RELEASE_VERSION}-Release`
  projectConfig.packOptions = { ignore: [], include: [] }
  projectConfig.setting = { ...projectConfig.setting, urlCheck: true }
  fs.writeFileSync(projectConfigPath, `${JSON.stringify(projectConfig, null, 2)}\n`)

  fs.writeFileSync(path.join(outputDirectory, 'config', 'runtime.js'), releaseRuntime(apiBaseUrl))
  fs.writeFileSync(path.join(outputDirectory, 'services', 'demo-runtime.js'),
    "// Remote release: local database and demo report generation are intentionally absent.\nmodule.exports = { repository: Object.freeze({}), aiProvider: Object.freeze({}) }\n")
  fs.writeFileSync(path.join(outputDirectory, 'RELEASE_BUILD.json'), `${JSON.stringify({
    schemaVersion: 3,
    productVersion: RELEASE_VERSION,
    generatedAt: new Date().toISOString(),
    runtimeMode: 'remote',
    artifactClass: offlineTest ? 'OFFLINE_TEST_ONLY' : 'STAGING_OR_RELEASE_BUILD',
    uploadAuthorized: false,
    externalConnectivityVerified: false,
    appid,
    apiOrigin: new URL(apiBaseUrl).origin,
    sourcePageCount,
    releasePageCount: appConfig.pages.length,
    includesPaidReportAgent: true,
    includesDualAgentAnalysis: true,
    includesEducationCompassV05: true,
    excludesLocalDatabase: true,
    excludesDemoReportGenerator: true,
    excludesServerSource: true,
    excludesOpenAiSdkAndServerPrompt: true
  }, null, 2)}\n`)

  return outputDirectory
}

if (require.main === module) {
  const output = buildRelease()
  const provenance = JSON.parse(fs.readFileSync(path.join(output, 'RELEASE_BUILD.json'), 'utf8'))
  console.log(`${provenance.artifactClass} build created: ${output}`)
}

module.exports = { buildRelease, DIST_ROOT, EXCLUDED, RELEASE_VERSION }
