const assert = require('node:assert/strict')
const labels = require('../models/masters-labels')
const fs = require('node:fs')
const path = require('node:path')
assert.equal(labels.targetYearLabel('UNDECIDED'), '尚未确定，希望顾问建议')
assert.equal(labels.targetYearLabel('2027'), '2027')
assert.equal(labels.fieldLabel('languageScores.subscores.writing'), '写作')
assert.equal(labels.contactTypeLabel('wechat'), '微信')
assert.equal(labels.studentValue('TRANSCRIPT'), '本科成绩单')
const read = file => fs.readFileSync(path.join(__dirname, '..', file), 'utf8')
const confirmation = read('pages/masters-confirm/index.wxml')
assert(!confirmation.includes('{{profile.targetYear}}') && !confirmation.includes('{{profile.contact.type}}'))
assert(!confirmation.includes('{{item.field}}') && !confirmation.includes('{{item.type}}'))
const report = read('pages/masters-report/index.wxml')
assert(report.includes('{{report.assistance.label}}') && report.includes('{{report.assistance.explanation}}'))
assert(report.includes('{{item.officialUrl}}') && report.includes('{{item.sourceStatusLabel}}'))
assert(!report.includes('{{report.status}}') && !report.includes('{{item.sourceStatus}}'))
console.log('✓ student report: Chinese labels, visible official source and server-derived assisted/initial report classification')
