const assert = require('node:assert/strict')
const { classifyResult, sanitized } = require('../scripts/verify-masters-candidate')
assert.equal(classifyResult('masters-postgres', 0, '{"status":"BLOCKED_EXTERNAL"}'), 'BLOCKED_EXTERNAL')
assert.equal(classifyResult('masters-postgres', 0, 'ℹ skipped 1'), 'BLOCKED_EXTERNAL')
assert.equal(classifyResult('masters-postgres', 0, '{"status":"PASS","suite":"masters-postgres","databaseConnectionAttempted":true}'), 'BLOCKED_EXTERNAL')
assert.equal(classifyResult('masters-postgres', 0, '{"status":"PASS","suite":"masters-postgres","databaseConnectionAttempted":true,"httpFlow":"PASS"}'), 'PASS')
assert.equal(classifyResult('masters-postgres', 1, '{"status":"PASS","suite":"masters-postgres","databaseConnectionAttempted":true,"httpFlow":"PASS"}'), 'FAIL')
assert.equal(classifyResult('all-regression', 0, 'ℹ skipped 0\nℹ fail 0'), 'PASS')
assert.equal(classifyResult('all-regression', 0, 'ℹ skipped 2'), 'BLOCKED_EXTERNAL')
assert.equal(classifyResult('release-build', 0, 'OFFLINE_TEST_ONLY'), 'OFFLINE_TEST_ONLY')
assert.equal(sanitized('synthetic-database-value', { MASTERS_TEST_DATABASE_URL: 'synthetic-database-value' }), '[REDACTED]')
console.log('✓ candidate evidence: zero-exit blocked/skipped DB cannot pass; PostgreSQL HTTP evidence and current clean HEAD required')
