const test = require('node:test')
const assert = require('node:assert/strict')
const path = require('node:path')
const web = path.resolve(__dirname, '../../website/phoenix-nova-website-v5')
const masters = require(path.join(web, 'lib/rc/application/masters-intake.cjs'))
const repo = require(path.join(web, 'lib/rc/family/repository.cjs'))
const store = require(path.join(web, 'lib/rc/family/store.cjs'))
const memory = new Map()
global.window = { sessionStorage: { getItem: key => memory.get(key) || null, setItem: (key,value) => memory.set(key,value) } }

test('Family browser adapter preserves member and timeline behavior from candidate', () => {
  store.reset()
  repo.insert('users', { id: 'rc_demo_test_adult', role: 'family_user' })
  const family = repo.upsertFamily('rc_demo_test_adult', { family_name: 'Synthetic', parent_name: 'Demo', phone: '', location: 'HK', goal: 'Learning' })
  const student = repo.upsertStudent(family.id, { name: 'Synthetic A' })
  assert.match(student.id, /^rc_demo_stu_/)
  assert.equal(repo.familyOverview(family.id).students.length, 1)
  assert.equal(repo.familyOverview(family.id).events.length, 2)
  repo.upsertFamily('rc_demo_test_adult', { family_name: 'Updated', parent_name: 'Demo', phone: '', location: 'HK', goal: 'Growth' })
  assert.equal(repo.where('families', f => f.user_id === 'rc_demo_test_adult').length, 1)
  assert.equal(repo.familyForUser('rc_demo_test_adult').family_name, 'Updated')
})
test('Family adapter uses its own RC key, leaving native storage untouched', () => {
  assert.equal(store.STORAGE_KEY, 'phoenix:rc:family:v1')
  assert.equal(memory.has('PFS_DB_V01'), false)
})
test('Family reload tolerates malformed demo storage', () => {
  window.sessionStorage.setItem(store.STORAGE_KEY, '{broken')
  assert.ok(Array.isArray(store.load().families))
})
test('Application cannot advance missing facts or missing adult confirmation', () => {
  const required = masters.requiredProfileFields(masters.emptyProfile())
  assert.ok(required.includes('adultConfirmed'))
  assert.ok(required.includes('institution'))
  const valid = masters.normalizeProfile({ name: 'Demo', adultConfirmed: true, contact: { type: 'email', value: 'demo@example.invalid' }, institution: 'Synthetic', major: 'Economics' })
  assert.deepEqual(masters.requiredProfileFields(valid), [])
})
test('Application material branching retains enrolled and graduated candidate rules', () => {
  const visible = status => masters.buildMaterialCards([], status, true).cards.filter(c => c.visible).map(c => c.type)
  assert.ok(visible('ENROLLED').includes('ENROLLMENT'))
  assert.equal(visible('ENROLLED').includes('DEGREE'), false)
  assert.ok(visible('GRADUATED').includes('DEGREE'))
  assert.ok(visible('GRADUATED').includes('GRADUATION'))
  assert.equal(visible('GRADUATED').includes('ENROLLMENT'), false)
})
test('Application draft does not invent scores, institution or language evidence', () => {
  const draft = masters.resumeDraft(masters.emptyProfile())
  assert.equal(draft.factsOnly, true)
  assert.match(draft.text, /待补/)
  assert.match(draft.text, /暂无可用成绩/)
  assert.equal(draft.text.includes('演示大学'), false)
})
test('Sample materials stay marked for human review and optional', () => {
  const result = masters.buildMaterialCards([{ id:'rc_demo_RESUME', type:'RESUME', name:'Synthetic.pdf', size:1024, uploadStatus:'UPLOADED', parseStatus:'MANUAL_REVIEW' }], 'ENROLLED', true)
  const resume = result.cards.find(c=>c.type==='RESUME')
  assert.equal(resume.optional, true)
  assert.equal(resume.files[0].parseStatus, 'MANUAL_REVIEW')
})
